# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # Expecting hostname "gluu.local" to map this IP address in the /etc/hosts file
  config.vm.network "private_network", ip: "192.168.33.30"

  config.vm.provider "virtualbox" do |vb|
    # Need a least 3GIG of RAM to run Gluu
    vb.memory = "3072"
  end

  # Install and configure gluu
  config.vm.provision "shell", inline: <<-SHELL
    echo "deb https://repo.gluu.org/ubuntu/ trusty main" > /etc/apt/sources.list.d/gluu-repo.list
    curl https://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add -
    apt-get update
    apt-get install -y gluu-server-2.4.3
    sudo /etc/init.d/gluu-server-2.4.3 start
    echo "Copy properties file for setup..."
    cp /vagrant/setup.properties.base /opt/gluu-server-2.4.3/install/community-edition-setup/setup.properties

    # Still need to figure out how to run these scripts
    # Because of the login command, shell does not respond in ssh. Need to connect to the vm to execute those lines
    #
    # sudo /etc/init.d/gluu-server-2.4.3 login
    # cd /install/community-edition-setup
    # ./setup.py

  SHELL
end
